// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3I5tVUlROza9d3lVnZO7CMGpuvpT82I',
    appId: '1:56524600949:web:a69a4183a51bf5d5efaa3c',
    messagingSenderId: '56524600949',
    projectId: 'chat-app-524f4',
    authDomain: 'chat-app-524f4.firebaseapp.com',
    storageBucket: 'chat-app-524f4.appspot.com',
    measurementId: 'G-EGPFP4SH9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDII5SpoWTjZUd6XJEdvUtQw1iKGxF9Xos',
    appId: '1:56524600949:android:d6fc73a468907565efaa3c',
    messagingSenderId: '56524600949',
    projectId: 'chat-app-524f4',
    storageBucket: 'chat-app-524f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3rD7lmaOXPP0qP1MOry_sBEvOozzzWU',
    appId: '1:56524600949:ios:63bc34071f73e429efaa3c',
    messagingSenderId: '56524600949',
    projectId: 'chat-app-524f4',
    storageBucket: 'chat-app-524f4.appspot.com',
    iosBundleId: 'com.example.chatAppClasswork',
  );
}
